spring:
  application:
    name: pequenoCesar
  profiles:
    default: dev
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/cesar_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: ${JWT_EXPIRATION_MS:900000}

decolecta:
  base-url: ${DECOLECTA_BASE_URL:https://api.decolecta.com}
  api-token: ${DECOLECTA_API_TOKEN:}
